feat: 피드백 페이지를 추가합니다.
mobi-production/ani-fe pull request #29
Opened 2024-11-15 16:09 UTC by JeongwooHam

## 🌱 작업 개요

- 피드백 질문 목록 및 피드백 페이지를 추가합니다.
- 피드백 mock data 파일을 추가합니다.
- PR 단위가 너무 커질 것 같아 `FeedbackStep` 클릭 시 queryString 변경 되는 부분과 msw로 피드백 데이터를 받아오고 제출하는 부분은 다음 PR로 나누어 올리도록 하겠습니다.
- 이전 PR들을 병합하면서 충돌이 생기는 부분을 수정하다보니 커밋량이 너무 많아졌네요..! 다음부터는 더 작은 단위로 올려보겠습니다🥲

## 🧐 중요한 변경 사항

> 피드백 페이지

<img src="https://github.com/user-attachments/assets/75c6951d-7711-43e9-9731-5b10ac6a0449" width="50%"/>

- `/path/123/detail/feedback` 과 같이 접근할 수 있습니다. Zero님께서 설정해주신 route 구조에 기반하여 수정하였는데 바꿔야 할 부분이 있다면 말씀해주세요!

> 공용 유틸 함수 `extractKeysFromObject` 추가

키 타입이 제한된 상황에서 `Object.Keys`를 사용할 때 단순히 `string[ ]`으로 추론 되어 타입 오류가 발생하는 상황을 방지하기 위해 해당 유틸 함수를 `shared` 파일에 추가해두었습니다. 이 함수를 통해 특정 객체의 키 타입으로 제한된 키 배열을 추출할 수 있습니다.

```tsx
export function extractKeysFromObject<T extends object>(object: T): Array<keyof T> {
  const keys: Array<keyof T> = []
  for (const key in object) {
    if (Object.hasOwnProperty(key)) {
      keys.push(key)
    }
  }
  return keys
}
```

자세한 사용법은 파일 내에 JSDocs로 작성해두었습니다.

## 👻 질문 사항

- [mobia-demo fsd written by Peanut](https://github.com/mobi-production/mobia-demo/blob/main/docs/fsd.md) 해당 문서를 참고하여 폴더 구조 및 파일 위치를 설정하였습니다. 임의로 결정한 부분들이 있다 보니 보시기에 어색한 부분 피드백 주시면 반영하여 수정하겠습니다🫠
- Widgets 폴더에 구현되어 있는 `MentoFeedback` ~ `PairFeedback` 컴포넌트들의 경우 모두 동일하고 제목이나 내부에 들어가는 데이터만 다른 구조이나 위에서 참고한 fsd 문서에 기반해 결합도를 낮추기 위해 분리한 컴포넌트들입니다. 이러한 경우에도 스토리북 파일을 모두 만들어야 할까요?🤔

2024-11-15 16:57 UTC, Zero-1016 approved these changes
고생하셨습니다 :)

체크된 부분만 확인하시면 될 것 같아요, 아마 이전 PR이 합쳐지고 나면 설정하는 데에 있어서 어려움이 없어 보일 것 같네요

2024-11-16 03:07 UTC, zivivle commented on apps/web/app/path/[pathId]/detail/[pageId]/page.tsx
> +    description: `${pathName} 패스 상세 페이지입니다.`
실제 사용자에게 보여지는 메타 데이터가 pathId로 보여져도 괜찮은걸까요?! 궁금해서 여쭤봅니다 :)

2024-11-16 03:11 UTC, zivivle commented on apps/web/src/shared/lib/utils/extract-keys-from-object.tsx
ㅎㅎ정말 좋은 함수네요! 👍👍👍

2024-11-16 03:15 UTC, zivivle commented on apps/web/src/widgets/feedback/ui/PartFeedback.tsx
> +  if (!PART_FEEDBACK_LIST) return
```js
// Bad case
if (!PART_FEEDBACK_LIST) return
// Good case
if (!PART_FEEDBACK_LIST) return null
```
React 컴포넌트에서 아무것도 렌더링하지 않을 경우 명확하게 return null을 사용하는 것이 좋은 패턴이라고 알고있습니다 :)

2024-11-16 03:21 UTC, zivivle approved these changes
모두 확인했습니다! 엄청 빠르게 작업해주셨네요! 👍
수고하셨습니다!

[질문에 대한 답변]
같은 구조의 화면이라면 스토리북 파일은 하나만 만들어도 괜찮지 않을까요? :)

2024-11-16 03:43 UTC, Zero-1016 requested changes
pr-check에서 에러나는 부분은 확인후 수정해서 올려주셔야 합니다!

2024-11-16 07:44 UTC, JeongwooHam commented on apps/web/src/widgets/feedback/ui/PairFeedback.tsx
> +    <div>
틀을 잡을 때 사용하고 `FeedbackList` 컴포넌트를 추가하면서 삭제하지 않았었네요..! [해당 PR](https://github.com/mobi-production/ani-fe/pull/29/commits/1514c3a3eb5d5b361cfe6b93ba8dd17de82e5250)에서 수정해두었습니다.

2024-11-16 07:44 UTC, JeongwooHam commented on apps/web/src/widgets/feedback/ui/PartFeedback.tsx
> +  if (!PART_FEEDBACK_LIST) return
[해당 PR](https://github.com/mobi-production/ani-fe/pull/29/commits/f60edfcd6f593d0ad45ed988783fcfa10bd58fc7)에서 수정해두었습니다:)

2024-11-16 07:44 UTC, JeongwooHam commented on apps/web/app/path/[pathId]/detail/[pageId]/page.tsx
> +    description: `${pathName} 패스 상세 페이지입니다.`
TODO에 적어둔 것처럼 패스와 파트 관련 데이터를 받아올 수 있게 되면 route에 사용된 id 값을 활용하여 패스/파트명이 들어가도록 수정할 계획이었습니다ㅎㅎ 우선 틀만 잡아뒀다고 생각해주세용🫠

2024-11-16 07:44 UTC, JeongwooHam commented on apps/web/app/path/[pathId]/detail/feedback/page.tsx
> +import FeedbackPage from '../../../../../src/pages/FeedbackPage'
오 감사합니다ㅎㅎ [해당 커밋](https://github.com/mobi-production/ani-fe/pull/29/commits/e7379a2fe88705fe06ee9f36b8321975e024c4a9)에서 수정해두었습니당

2024-11-16 07:44 UTC, JeongwooHam commented on apps/web/src/widgets/feedback/ui/PartFeedback.tsx
mobia-demo에 작성된 fsd 관련 문서에서 `widgets` 관련된 내용(아래에 붙여넣어 두었습니다.)을 보고, zero님처럼 폼도 같고 카테고리만 달라서 하나로 합칠까 하다가 우선 스텝별로 컴포넌트를 분리해두었습니다. 구조상 파트/멘토/페어 피드백 문항 목록은 한번에 query로 조회하고 하나의 mutation으로 응답 값을 제출할 것 같아 그냥 하나의 UI로 관리하고 props로 피드백 문항 목록만 넘겨줘도 될 것 같긴 합니다. 

팀원분들과 협의된 구조는 아니어서 불필요하다고 생각하시면 하나로 통일하겠습니다ㅎㅎ


### widgets

widget은 독립적으로 사용할 수 있는 interface component입니다. 자체만으로 하나의 역할을 부여받기 때문에 비즈니스에 필요한 설계가 정의되는 곳이기도 합니다.

```
// before
const PostList = ({ type }) => {
  const { data } = useFetchPostList(type);
  // type에 따라 호출하는 post가 다르게 설계
};

// after
const PostList = () => {
  const { data } = useFetchPostList();
  // ... your interface
};

const PostPopularList = () => {
  const { data } = usePopularPostList();
  // ... your interface
};
```

before는 외부에서부터 type을 주입받아 type에 따라 다른 PostList를 정의합니다. 그러나 이는 popular-post와 - all-post로부터 커플링을 발생시키고 훗날 interface의 개선이 필요할 때 확장이 어려운 베이스의 코드가 생산됩니다. fsd는 명확한 역할에 따라 사용가능한 레이어를 최소화하여 느슨한 결합을 만드는 것을 목표로 하고 있습니다. 따라서 after과 같이 하나의 역할을 부여받은 컴포넌트가 사용되는 레이어를 명확하게 함으로서 그 사이에 있는 관계를 느슨하게 만들 수 있습니다

widgets의 가장 큰 핵심은 무분별한 재사용보다 부여받은 역할이 있는 레이어 만들기 입니다.

2024-11-16 08:37 UTC, Zero-1016 approved these changes

2024-11-16 08:39 UTC, merged