feat: 공용 모달 컴포넌트를 추가합니다.
mobi-production/ani-fe pull request #46
Opened 2024-11-23 11:49 UTC by JeongwooHam

## 🌱 작업 개요

- `packages/ui`에 공용 모달 layout을 추가했습니다.
- `shared/ui`에 Next.js에서의 `Portal` 컴포넌트를 추가했습니다.
- `shared/ui`에 ANI에서 사용하는 공용 모달(ConfirmModal, AlertModal)을 추가했습니다.

![image](https://github.com/user-attachments/assets/98de68fc-ed8f-4a79-95b6-ff5f673dc32f)

- 녹색 원형 아이콘 이미지 에셋을 `public` 폴더에 추가했습니다.
- 기타 모달 디자인 상에서 사용되는 아이콘들을 IconMap에 추가했습니다.

## 🧐 중요한 변경 사항

> `Portal`

```tsx
import ReactDOM from 'react-dom'

function Portal({ children }: PropsNeedChildren) {
  const portalElement = typeof window !== 'undefined' && document.querySelector('#portal-container')

  return portalElement && children ? ReactDOM.createPortal(children, portalElement) : null
}

export default Portal
```

Portal 컴포넌트는 주어진 자식 요소를 `#portal-container`라는 ID를 가진 DOM 요소에 렌더링하여, 부모 컴포넌트의 DOM 트리 외부에서 표시되도록 합니다. ([참조 문서](https://ko.legacy.reactjs.org/docs/portals.html))

> `packages/ui` 공용 모달

모달 특성상 전체 프로젝트에서 공용으로 사용할 수 있으려면 자유도가 높아야 한다고 생각하여 `BackDrop`, `Overlay` 이외에는 `children`으로 받아 사용할 수 있도록 구현하였습니다. `BackDrop`과 `Overlay` 좌측 상단의 Close 버튼 또한 props를 통해 비활성화 처리할 수 있습니다.  

## 👻 질문 사항

> `svg` 이미지 추가

- OutlineCircle의 경우 Ant Design Icon에 존재하지 않아 figma 상에서 추출하여 사용하였습니다. 처음에는 WebP -> PNG 파일 순으로 적용을 시도하였으나 이 경우 아래와 같이 하단에 미세하게 잘리는 부분이 발생하였습니다. SVG로 추출하였을 때는 이 문제가 발생하지 않아 우선 해당 확장자를 사용하였는데 피드백 주시면 해당 방법을 사용해보겠습니다.

> 문제 상황쳐
 
![스크린샷 2024-11-23 201456](https://github.com/user-attachments/assets/4b4676f9-0c61-4e7d-87c0-e1cf254a3687)

2024-11-23 12:14 UTC, zivivle commented on apps/web/src/shared/ui/modal/Portal.tsx
👍 👍 👍

2024-11-23 12:16 UTC, zivivle approved these changes
포탈에 대해 알게 되었네요ㅎㅎ! 감사합니다!
모두 확인했습니다 :) 고생 많으셨습니다!

2024-11-23 17:34 UTC, Zero-1016 requested changes
고생하셨습니다.

현재 스토리북을 통해 모달을 열었을 때 다음과 같이 화면이 나타나게 됩니다.

![image](https://github.com/user-attachments/assets/63e1e71e-7af5-49a2-bb69-7b20cd2c3aaa)

portal에 z-index를 9999를 주는것도 좋은 방법이라고 생각이 되네요 :)

2024-11-23 17:34 UTC, Zero-1016 commented on apps/web/src/shared/ui/modal/Portal.tsx
P4

"포탈이라는 친구가 과연 Modal에만 한정 지을 수 있을까?"라는 생각을 하게 되네요, toast 메시지나 오른쪽 하단 채팅 아이콘과 같은 것들 모두 포탈을 이용해서 구현할 수 있을 것 같아요

2024-11-23 17:34 UTC, Zero-1016 commented on packages/ui/src/components/modal/index.tsx
> +    <div className='flex justify-end'>
P5

Flex 컴포넌트와 Icon의 size props을 이용하면 className을 따로 명시를 하지 않아도 사용이 가능할 것 같습니다. 직접 구현하지 않고 해당 방법을 사용하시는건 어떤가요?

2024-11-24 03:08 UTC, JeongwooHam commented
@Zero-1016 

> portal에 z-index를 9999를 주는것도 좋은 방법이라고 생각이 되네요 :)

혹시 이게 어떤 방식을 말씀하시는 걸까요..?🧐 Storybook Preview 파일에 정의된 `<div id="portal-container"></div>` 부분에 스타일을 적용하는 걸 의미하신 건가요??

2024-11-24 03:16 UTC, Zero-1016 commented
> @Zero-1016
> 
> > portal에 z-index를 9999를 주는것도 좋은 방법이라고 생각이 되네요 :)
> 
> 혹시 이게 어떤 방식을 말씀하시는 걸까요..?🧐 Storybook Preview 파일에 정의된 `<div id="portal-container"></div>` 부분에 스타일을 적용하는 걸 의미하신 건가요??

예를들어 다음과 같이 만들 수 있을 것 같아요

```tsx
function Portal({ children }: PropsNeedChildren) {
  let portalElement = 
    typeof window !== 'undefined' && document.querySelector('#portal-container');

  if (!portalElement && typeof window !== 'undefined') {
    portalElement = document.createElement('div'); // 새 div 생성
    portalElement.id = 'portal-container'; // id 설정
    portalElement.style.zIndex = '9999'; // z-index 추가
    portalElement.style.position = 'fixed'; // fixed로 설정 (예시)
    portalElement.style.top = '0';
    portalElement.style.left = '0';

    document.body.appendChild(portalElement);
  }

  return portalElement && children ? ReactDOM.createPortal(children, portalElement) : null;
}
```

2024-11-24 03:30 UTC, JeongwooHam commented on apps/web/src/shared/ui/modal/Portal.tsx
[Modal 폴더를 Portal 폴더로 변경](https://github.com/mobi-production/ani-fe/pull/46/commits/9f780d682a5e889260ceba09aaa1cc6d9470cab9) 커밋에서 수정해봤습니다. `Portal`을 최상위 `shared/ui` 컴포넌트로 보고, 하위에 말씀해주신 것처럼 `modal`, `toast` 등이 들어가는 구조를 생각했는데 어떠신지 피드백 부탁드립니다ㅎㅎ

2024-11-24 03:31 UTC, JeongwooHam commented on packages/ui/src/components/modal/index.tsx
> +    <div className='flex justify-end'>
[ClassName 사용하지 않도록 수정](https://github.com/mobi-production/ani-fe/pull/46/commits/981373b0bfaecc8b16899d37bf9807c7f564355e) 커밋에서 수정해두었습니다!

2024-11-24 03:38 UTC, zivivle commented on apps/web/app/layout.tsx
> +          <div id='portal-container'></div>
혹시 이 코드는 지워도 괜찮은 코드일까요?

2024-11-24 03:49 UTC, zivivle commented on apps/web/app/layout.tsx
> +          <div id='portal-container'></div>
안되는 군요! 부모의 gap-[3.25rem] css때문에 헤더위에 공간이 생겨버려서 gap-[3.25rem]를 지우고 header를 감싸는 css를 추가하는 방식으로 수정해놓겠습니다! :)

2024-11-24 03:53 UTC, JeongwooHam commented on apps/web/app/layout.tsx
> +          <div id='portal-container'></div>
넵넵 해당 코드는 전역에서 Portal을 사용하기 위해 추가해둔 영역이어서 아예 삭제할 경우 Portal이 보이지 않을 것 같아요..! 스타일 수정해주셔서 감사합니다🥹

2024-11-24 03:57 UTC, Zero-1016 approved these changes

2024-11-24 03:59 UTC, merged